notebook_metadata_filter = "-all"
cell_metadata_filter = "-all"

[[formats]]
"notebooks/user-guide/" = "ipynb"
"docs/user-guide/" = "md"

[[formats]]
"notebooks/case-studies/" = "ipynb"
"docs/case-studies/" = "md"
