[project]

site_name = "Affinis"

site_description = "Tools for inferring relations from binary co-occurrence data"
site_author = "Rachael Sexton"
site_url = "https://pages.nist.gov/affinis/"

copyright = """
Affinis and all of it's associated documentation are in the public domain (see the <a href="https://github.com/usnistgov/affinis/blob/main/LICENSE.md"> license </a>)
"""
nav = [
  {"Home" = "index.md"},  
  {"Installation" = "install.md"},
  {"Contributing" = "contributing.md"},
  { "User Guide" = [
      "user-guide/associations.md",
      "user-guide/smoothing.md",
      "user-guide/dist-prox.md",
        # "using/psdct.md"
    ]},
  {"Examples" = ["case-studies/example.md"]},
  { "API" = [
        'api/associations.md',
        'api/plots.md',
        'api/priors.md',
        'api/proximity.md',
        'api/distance.md',
        'api/filters.md',
        'api/types.md',
        
  ]},
]
extra_css = [
  "https://pages.nist.gov/nist-header-footer/css/nist-combined.css",
  "css/mkdocstrings.css"
]
extra_javascript = [
  "javascripts/mathjax.js",
  "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
  "https://pages.nist.gov/nist-header-footer/js/jquery-1.9.0.min.js",
  "https://pages.nist.gov/nist-header-footer/js/nist-header-footer.js",
]


[project.theme]

favicon = "images/favicon.png"
language = "en"

features = [
    "announce.dismiss",
    #"content.action.edit",
    #"content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    # "header.autohide",
    # "navigation.expand",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    #"navigation.instant.progress",
    "navigation.path",
    #"navigation.prune",
    "navigation.sections",
    #"navigation.tabs",
    #"navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    # "toc.follow",
    #"toc.integrate",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Rubik"
code = "Fira Code"

[[project.extra.social]]
name = "USNISTGOV on GitHub"
icon = "fontawesome/brands/github"
link = "https://github.com/usnistgov/affinis"

### Markdown Ext. 
[project.markdown_extensions.attr_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.admonition]

### pymdownx
[project.markdown_extensions.pymdownx.arithmatex]
generic=true
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style=true
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

### mkdocstrings
[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["affinis/"]
[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
# show_source = false
# backlinks = "tree"
docstring_options = {ignore_init_summary = true}
docstring_section_style = "list"
# extensions = ["griffe_typingdoc",]
filters = ["!^_", "^__"]
heading_level = 1
# merge_init_into_class = true
parameter_headings = true
separate_signature = true
show_root_heading = true
show_root_full_path = false
show_signature_annotations = true
show_source = true
show_symbol_type_heading = true
show_symbol_type_toc = true
show_docstring_type_aliases = true
signature_crossrefs = true
summary = true
unwrap_annotated = true

